services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MELHOR_CAMBIO_BASE_URL=https://www.melhorcambio.com
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data
    depends_on:
      - redis

volumes:
  redisinsight:
